### ISSUE TITLE
Expand the cookies categories

### ISSUE THREAD

**Issue by fellyph** [jkwakman/Open-Cookie-Database#149]
** Description **
Currently, the Open Cookie Database is listing cookies mainly with the following categories: 

- Marketing 
- Analytics
- Functional

The suggestion is to expand the categories to:

- Security
- Marketing
- Functional
- Personalization
- Analytics

** Motivation **
These categories are designed with the user in mind, aiming to provide a more user-friendly and transparent experience by better-translating cookie usage. 

Categories based on Google Cookies policies
https://policies.google.com/technologies/cookies?hl=en-US

**Comment by jkwakman** [comment]
Dear Fellyph,

Thank you for your valuable input. I think it would be a very good idea to make this adjustment. This is also much more in line with Google Consent Mode. I will update the category descriptions in the readme.md file and adjust the Github action so that these categories are possible to add in the CSV file.

**Comment by jkwakman** [comment]
Security, Marketing, Functional, Personalization and Analytics are now the defined categories. Categories are added to the readme.md and github action for validation.

**Comment by jkwakman** [comment]
@fellyph Can you add the new contribution document as a PR?
